### ISSUE TITLE
How do I install this in Android Studio?

### ISSUE THREAD

**Issue by wesleybliss** [ArtSabintsev/Cognac#1]
**Expected:**
Sexy themin'.

**Actual:**
I drag & drop it but all I see is gibberish.

**Comment by ArtSabintsev** [comment]
Need to make an Android Studio theme!

**Comment by ArtSabintsev** [comment]
You should make it :)

**Comment by wesleybliss** [comment]
I did, haha. But your repo structure doesn't make for easy PRs. Create the IDEA/IntelliJ repo & I'll PR it
![cognac-intellij](https://cloud.githubusercontent.com/assets/423683/26608938/452cb5f2-456c-11e7-934f-f36b870a1fff.png)

**Comment by ArtSabintsev** [comment]
Looks good!

Make a separate repo on your name, and I'll link off to it.

**Comment by ArtSabintsev** [comment]
btw, all the pink types should be bold ;)

**Comment by wesleybliss** [comment]
> btw, all the pink types should be bold

Could just be my specific AS settings. Otherwise, make a bug report, lol.

**Comment by ArtSabintsev** [comment]
Here are the specific rules ;)

https://github.com/ArtSabintsev/Cognac#specific-rules

**Comment by ArtSabintsev** [comment]
Merged your stuff. Thanks :)
