### ISSUE TITLE
iTerm2 Theme

### ISSUE THREAD

**Issue by dtgay** [ArtSabintsev/Cognac#4]
An official port of the Terminal.app theme to iTerm2 would be awesome.

Thank you for Cognac, I absolutely love it. I've been using it everywhere I can.

**Comment by ArtSabintsev** [comment]
I'm happy to hear you love it! I'll add this to my to-do list for one of the upcoming weekends!

**Comment by ArtSabintsev** [comment]
I moved over to iTerm this past week.

Here you go: https://github.com/ArtSabintsev/Cognac-iTerm

**Comment by dtgay** [comment]
This is **awesome**, thank you!

**Comment by ArtSabintsev** [comment]
My pleasure! I switched to iTerm at the same time I switched to VS Code. Loving both of them!
