### ISSUE TITLE
VSCode Theme

### ISSUE THREAD

**Issue by dtgay** [ArtSabintsev/Cognac#5]
[VSCode](https://code.visualstudio.com/) is getting pretty popular as a cross-platform editor, with many Sublime and Atom users switching over. A port would be awesome.

**Comment by ArtSabintsev** [comment]
Sorry! Didn't see this message now. 

I added the theme: https://github.com/ArtSabintsev/Cognac-VSCode

I recently switched to VSCode, so I'll be tweaking the theme as I come across issues.

**Comment by dtgay** [comment]
**Awesome**, thank you!! x2

**Comment by ArtSabintsev** [comment]
My pleasure!
